### ISSUE TITLE
broken in 2.3.1, possibly 2.3

### ISSUE THREAD

**Issue by andrewkett** [8WireDigital/magento2-module-primer#6]
PHP Fatal error:  Uncaught Error: Class 'GuzzleHttp\Client' not found in /var/www/src/vendor/eightwire/magento2-module-primer/Model/Crawler.php:60
Stack trace:
#0 /var/www/src/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(116): EightWire\Primer\Model\Crawler->__construct(Object(EightWire\Primer\Model\PageRepository), Object(Magento\Framework\Logger\Monolog), Object(Magento\Store\Model\StoreManager), Object(Magento\Framework\App\ObjectManager), Object(Magento\Framework\App\Config), Object(Magento\Framework\App\Cache\Manager), Object(EightWire\Primer\Helper\Config))
#1 /var/www/src/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('EightWire\\Prime...', Array)
#2 /var/www/src/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('EightWire\\Prime...')
#3 /var/www/src/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectM in /var/www/src/vendor/eightwire/magento2-module-primer/Model/Crawler.php on line 60

**Comment by andrewkett** [comment]
PHP Fatal error:  Uncaught Error: Class 'GuzzleHttp\Client' not found in /var/www/src/vendor/eightwire/magento2-module-primer/Model/Crawler.php:60
Stack trace:
#0 /var/www/src/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(116): EightWire\Primer\Model\Crawler->__construct(Object(EightWire\Primer\Model\PageRepository), Object(Magento\Framework\Logger\Monolog), Object(Magento\Store\Model\StoreManager), Object(Magento\Framework\App\ObjectManager), Object(Magento\Framework\App\Config), Object(Magento\Framework\App\Cache\Manager), Object(EightWire\Primer\Helper\Config))
#1 /var/www/src/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('EightWire\\Prime...', Array)
#2 /var/www/src/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('EightWire\\Prime...')
#3 /var/www/src/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectM in /var/www/src/vendor/eightwire/magento2-module-primer/Model/Crawler.php on line 60

**Comment by makhnovskiy** [comment]
What was the issue? Guzzle not required in composer file?

**Comment by andrewkett** [comment]
Yea we had Guzzle in all our Magento sites from another external dependancy. It wasn't until we installed on a clean 2.3 project that we realised the dependancy was missing from this module. This was resolved in 0.1.10.
