### ISSUE TITLE
Invallid URL with Store Code in Urls 

### ISSUE THREAD

**Issue by figinternet** [8WireDigital/magento2-module-primer#7]
When having a multi-store setup, with the option:
Store->Configuration-> General -> Web -> Add Store Code to Urls to enabled.

In the DB is the product url:
- /nl/product1.html
- /en/product1.html

And the crawlers is trying to visited:
`www.example.org/nl/nl/product1.html`
Instead of:
`www.example.org/nl/product1.html`

I Think this is because the Database entry contains the Store Code and the function getStoreUrl() inside /Model/Page.php at Line 118 is getting the StoreUrl also with the Storecode.

**Comment by andrewkett** [comment]
I can replicate this, I need to fix it for an upcoming build of ours. I think the best approach would be to strip the store code from the saved path in the log table. That way the crawler would still work with logged urls regardless of the setting being on or off.

**Comment by andrewkett** [comment]
This is fixed in 0.1.12 release
